version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://localhost:27017/lms_db  # Connect to local MongoDB
    volumes:
      - .:/LMS_BACKEND
    command: pipenv run python manage.py runserver 0.0.0.0:8000